Add the duplicate command

diff --git a/dist/bin/tsm b/dist/bin/tsm
--- a/dist/bin/tsm
+++ b/dist/bin/tsm
@@ -488,6 +488,38 @@ function __tsm::commands::doctor::legacy() {
   builtin print
 }
 
+function __tsm::commands::duplicate() {
+  local session_name="$1"
+  if [[ -z "$session_name" ]]; then
+    __tsm::utils::log error "Missing session name"
+    __tsm::commands::help::copy
+    return 1
+  fi
+
+  local session_file
+  session_file="$TSM_SESSIONS_DIR/$session_name"
+  [[ "${session_file:e}" == "txt" ]] || session_file+=".txt"
+
+  if [[ ! -f "$session_file" ]]; then
+    __tsm::utils::log error "Session not found: ${session_name}"
+    builtin print
+    __tsm::commands::list
+    return 1
+  fi
+
+  integer -l index=1
+  local new_session_name new_session_file
+
+  while true; do
+    new_session_name="${session_name}${index}"
+    new_session_file="$TSM_SESSIONS_DIR/${new_session_name}.txt"
+    [[ -f "$new_session_file" ]] || break
+    (( index++ ))
+  done
+
+  __tsm::commands::copy "$session_name" "$new_session_name"
+}
+
 function __tsm::commands::help() {
   local cmd="$1"
   [[ "$cmd" == "tsm" ]] && { __tsm::commands::tsm ; return $status }
@@ -535,6 +567,13 @@ Help-Message
 function __tsm::commands::help::copy() {
   cat <<Help-Message
 Usage: tsm copy <name> [new-name]
+Help-Message
+  return 64
+}
+
+function __tsm::commands::help::duplicate() {
+  cat <<Help-Message
+Usage: tsm duplicate <name>
 Help-Message
   return 64
 }
